# Generated by Django 2.1.3 on 2018-12-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default='testing', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
